* 2016-Apr-11-Monday:
- I have gone through the =Linux Lab= which is available at *Vlabs.ac.in*  [[http://cse09-iiith.virtual-labs.ac.in/][here]]. And done all the following experiments.
  * File Management
  * Text Editor
  * File Content
  * File Permissions
  * Archival and Compression
  * Obtaining System Information
  * Pipes and Redirection
  * Searching
  * Basic Networking 

* 2016-Apr-12-Tuesday:
- I have Practised and revised KVM Virtualization Technique by Creating and deleting Snapshots, in that I installed windows OS, Ubuntu OS and Created snapshots too.

* 2016-Apr-13-Wednesday:
- I have gone through the AWS(Amazon Web Services) EC2 Cloud technique and read about various articles from online which can be found [[https://aws.amazon.com/what-is-cloud-computing/?nc2=h_l2_cc][here]].
  And got the clear picture on following concepts.
 * What is AWS?
 * What is Cloud Computing?, How does it works?, Types of Cloud Computing and Advantages of Cloud Computing.
- Created my own AWS account to practice EC2.
- Created multiple AWS EC2 VMs which are =free-tier=.
* 2016-Apr-14-Thursday:
- Today Ashay assigned me a task. The task is to install Dual Operating System (Windows7 & Ubuntu 14.04 LTS 64 bit) and install all the required packages as per *RAVI*'s requirement.
- I choose Windows7 64 bit as first OS and Ubuntu14.04 64 bit as second OS.
- I have installed OS through USB, by making USB as bootable pendrive using =unetbootin= tool.
- After successful installation of both the OS’s. I restarted my machine to check whether grub entries are there or not.
- I couldn’t see the grub entries for Windows OS. (I don't know the reason why???) 
  Then I logged into the Ubuntu machine and updated the grub using the command “grub-update”.
- Then I could see both OS’s grub entries.

* 2016-Apr-15-Friday:
- I resumed my work on setting up *RAVI's* machine and I installed all the required packages on Ubuntu14.04 OS, I have installed the following below packages
 * Git 1.7.0
 * Emacs 24.5 with =org-mode= version 8.3.4 
 * Skype 4.3
 * Thunderbird Mail
 * Google-Chrome
 * Hex Chat
 * Sublime Text Editor
 * VirtualBox
 * Setting up proxy globally on following file
#+begin_example
$ vi ~/.bashrc
#+end_example
 * And I Entered the follwing proxy settings
  + export http_proxy="http://proxy.iiit.ac.in:8080"
  + export https_proxy="http://proxy.iiit.ac.in:8080"
