* (2016-07-11 Monday)
  - Learnt indetail the model of the systems cluster at VLEAD. The
    tools, systems, configurations, setup files and related
    discussions are all part of the model.
  - Read about Base1, Base4 and AWS clusters.
* (2016-07-12 Tuesday)
  - Customizing the OrangeHR-Management portal and tested whether attendance, email notifications and leave management is working or not.
  - I read about DNS servers and Reverse proxy server. 
* (2016-07-13 Wednesday)
  - Read about Nagios, rsyslog_server and router.
  - Checking alerts for VLEAD
  Monitoring the services using nagios webpage.  I will be
getting alerts also from nagios if any service is in critical state or
if any service went down/stopped running.

Especially, I am checking disk space of Outreach portal VM everyday
as well as all the lab VMs.
* (2016-07-14 Thursday)
  - Generated employee attendance daily and month wise reports for Orangehrm portal using below process.
1). Use database
2). listing punch in/out for all the users time.
3). listing all employee numbers and employee username.
4). Joining two tables, why because emp_number and employee_id common on both tables. by doing this we can get user_name and emp-number.
Generating employee attendance reports is done successfully
* (2016-07-15 Friday)
  - Implemantation of  automation script for generating employee attendance.
  - It will generate the following reports with in-time and out-time details for each employee.
1. day wise reports and
2. Monthly wise reports
 
