* 2016-Apr-04-Monday:
- I have practised and Revised all baisics of Networking concepts and SSH-Server.
* 2016-Apr-05-Tuesday:
- I have gone through bridge networking, I installed bridge, setup bridge and configured containers.
* 2016-Apr-06-Wednesday:
- Today I took Python Programming Language and I have read about lists, tuples and string concepts.
- After I finished reading complete chapters. I am solving all the problem related to that chapter.
- Here I have listed all the exercise that I have done so far.
** Exercise1.
- Iterations, for and while loops.
** Exercise2.
- Strings, string sequences, string with loop, string comparison and string methods.
** Exercise3.
- what is lists?, list of sequense, list operations, list methods, list arguments and list with functions.
** Exercise4.
- what is tuples?, comparing tuples and sequenses of strings,lists and tuples.
* 2016-Apr-07-Thursday:
- I resumed my work on Python Programming Language.
** Exersice5.
- I have implemented source code for Looping concepts, string, lists and tuples.
* Script-1
- Executed the script using command
#+begin_example
chmod +x loop.py
./install.py
#+end_example
- Script has the following code
#+begin_example
#!/usr/bin/python
# Sample for loop to print welcome message 3 times
for i in '123':
        print "Welcome",i,"times"


# Iterating python for loop using range() function
# Python for loop using range()
 
print "*** Generates a list of 3 values starting from 0 ***"
for i in range(3):
        print "Welcome",i,"times."
 
print "*** Generates a list of 3 values starting from 1 ***"
for i in range(1,4):
        print "Welcome",i,"times."



# Prints out 0,1,2,3,4 using while loop
count = 0
while count < 5:
    print count
    count = count + 1 


# Prints out 0,1,2,3,4 using break statement.
count = 0
while True:
    print count
    count = count + 1
    if count >= 5:
        break

# Prints out only odd numbers - 1,3,5,7,9 using continue statement.
for x in xrange(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print x
#+end_example

* Script-2
- Executed the script using command
#+begin_example
chmod +x string.py
./install.py
#+end_example
- Script has the following code
#+begin_example
#!/usr/bin/python
# Assign three string charecters to a, b and c variables. And we print them to console.
a = "raghu"
b = "pathi"
c = "kammari"
print a
print b
print c

# Finding the length of a string 
# The len() method calculates the number of characters in a string.
a = "1234"
b = "raghu"
c = "welcome"
print len(a)
print len(b)
print len(c)


# Finding Comparingg two strings
print "aa" == "aa"
print "ab" == "aa"
print "12" == "12"
print "120" == "1123"


# Print three columns of numbers.

for x in range(1,11):
    print '%d %d %d' % (x, x*x, x*x*x)
#+end_example


* Script-3
- Executed the script using command
#+begin_example
chmod +x list.py
./install.py
#+end_example
- Script has the following code
#+begin_example
#!/usr/bin/python
# Print list 6 elements and accessed by their index.
no = [1,"raghu","welcome",4,5,6]
print no

# Print list 5 elements and assigned by their index. And we print comparing two variables.

x = [1, 2, 3, 4, 5]
y = [3, 4, 5, 6, 7]

print x == x
print x + y

print x * 3

print 2 in x
print 2 in x



# Finding length, max, mina and sum of given values using sequence functions

n = [1, 2, 3, 4, 5, 6, 7, 8]

print "There are %d items" % len(n)
print "Maximum is %d" % max(n)
print "Minimum is %d" % min(n)
print "The sum of values is %d" % sum(n)
#+end_example
