* (2016-09-06 Tuesday)
  -  Hosted couple of labs on staging environment.
  -  Lab performance testing for CPU and RAM usage an each lab. And created excel
     sheet for each lab information such as concurrent users,
     transaction rate, CPU and RAM.
  - Checking cumulative analytics of virtual-labs.
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - Amazon monitoring update During all this timings along with the alert mails, following things were monitored:
1. AWS instance​s and their graphs
2. AWS billing
* (2016-09-07 Wednesday)
  -  Lab performance testing for CPU and RAM usage an each lab. And created excel
     sheet for each lab information such as concurrent users,
     transaction rate, CPU and RAM.
  - Checking cumulative analytics of virtual-labs.
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - Amazon monitoring update During all this timings along with the alert mails, following things were monitored:
1. AWS instance​s and their graphs
2. AWS billing
