* 2016-Apr-04-Monday:
- I have practised and Revised all baisics of Networking concepts and SSH-Server.
* 2016-Apr-05-Tuesday:
- I have gone through bridge networking, I installed bridge, setup bridge and configured containers.
* 2016-Apr-06-Wednesday:
- Today I took Python Programming Language and I have read about lists, tuples and string concepts.
- After I finished reading complete chapters. I am solving all the problem related to that chapter.
- Here I have listed all the exercise that I have done so far.
** Exercise1.
- Iterations, for and while loops.
** Exercise2.
- Strings, string sequences, string with loop, string comparison and string methods.
** Exercise3.
- what is lists?, list of sequense, list operations, list methods, list arguments and list with functions.
** Exercise4.
- what is tuples?, comparing tuples and sequenses of strings,lists and tuples.
* 2016-Apr-07-Thursday:
- I resumed my work on Python Programming Language.
** Exersice5.
-
- I have implemented source code for Looping concepts, string, lists and tuples.
* Script-1
- Executed the script using command
#+begin_example
chmod +x loop.py
./install.py
#+end_example
- Script has the following code
#+begin_example
#!/usr/bin/python
# Sample for loop to print welcome message 3 times
for i in '123':
        print "Welcome",i,"times"


# Iterating python for loop using range() function
# Python for loop using range()
 
print "*** Generates a list of 3 values starting from 0 ***"
for i in range(3):
        print "Welcome",i,"times."
 
print "*** Generates a list of 3 values starting from 1 ***"
for i in range(1,4):
        print "Welcome",i,"times."



# Prints out 0,1,2,3,4 using while loop
count = 0
while count < 5:
    print count
    count = count + 1 


# Prints out 0,1,2,3,4 using break statement.
count = 0
while True:
    print count
    count = count + 1
    if count >= 5:
        break

# Prints out only odd numbers - 1,3,5,7,9 using continue statement.
for x in xrange(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print x
#+end_example
