* 2016-Feb-25-Thursday
** From 9:30 AM TO 12:30 PM :
  - As I came to know that VLEAD is completely using open source
    technologies. I took a very first step to install an Operating System on my
    desktop machine.
  - There are multiple ways to install an Operating Systems on any
    desktop/server machine, those are 
    + Through USB
    + Through CD-ROM
    + Through Network Boot
    + Through Floppy Disk
  - To install OS I have chosen CentOS 6.5 64 bit distribution of Linux. Why because
    all the servers at vlead using CentOS as a OS.
  - I have installed OS through USB, CD-ROM and it worked well.

** From 2:00 PM TO 6:00 PM :

 -  And also I tried to install OS through Network Boot and  during installation I faced
    few issues then, I took team members to
    resolve the issue and it worked well.
 -  As it is possible to install multiple operating systems on any desktop/server
    machine I tried to make dual boot my machine. I choose CentOS 6.5 64 bit as
    first machine and Ubuntu12.04 32 bit as second OS.
 -  After successful installation of both the OS's. I restarted my machine to
    see the OS kernel entries on grub list and I could see both the os's kernel
    list
 
* 2016-Feb-26-Friday
** From 9:30 AM TO 12:30 PM :
  - I resumed my work on installing operating system. This time I tried to
    install Windows OS and on top of it I installed Ubuntu Machine.
  - After successful installation of both OS's. I restarted my machine to check
    whether grub entries are there or not.
  - I couldn't see the grub entries for Windows OS. Then I logged into the
    Ubuntu machine and updated the grub using command "grub-update".
  - Then I could see both OS's grub entries.

** From 2:00 PM TO 6:00 PM :
  - I started taking online course on Linux and Shell Commands. And completed 3
    video lectures and done the assignment as well. Through which I came to learn following commands
    + cd - cd directory, cd ., cd .., cd /
    + ls - ls, ls -l, ls -a and ls -lrt
    + cp - cp source destination, cp -r source destination,
    + mv - mv source destination
    + rm - rm filename, rm -f filename, rm -rf foldername
    + mkdir - mkdir dirname
    + rmdir - rmdir dirname
    + touch - touch filename
    + cat -  cat filename, cat > filename, cat >> filename.
    + chmod - chmod -R rwxrwxrwx file/foldername
* 2016-Feb-27-Saturday
** From 9:30 AM TO 5:00 PM :
I have gone through the =git= tutorial which is available at [[https://githowto.com/][here]] and learned some basic commands that includes following commands and also I read about difference between =git= tool and =github.com= , =bitbucket.com= and tried to create multiple repositories at =github.com= & =bitbucket.com= and executed the following commands and got know the uses of following commands
+ git config --global user.name "username"
+ git config --global user.email "emailid"
+ git config --global http.proxy http://proxy.iiit.ac.in:8080
+ git config --global https.proxy http://proxy.iiit.ac.in:8080
+ git init 
+ git add filename
+ git commit -m "commit message here"
+ git push origin master
+ git clone repo_url
+ git log
+ git status
+ git remote -v
+ git pull origin master
