* 2016-Apr-04-Monday:
- I have practised and Revised all baisics of Networking concepts and SSH-Server.
* 2016-Apr-05-Tuesday:
- I have gone through bridge networking, I installed bridge, setup bridge and configured containers.
* 2016-Apr-06-Wednesday:
- Today I took Python Programming Language and I have read about lists, tuples and string concepts.
- After I finished reading complete chapters. I am solving all the problem related to that chapter.
- Here I have listed all the exercise that I have done so far.
** Exercise1.
- Iterations, for and while loops.
** Exercise2.
- Strings, string sequences, string with loop, string comparison and string methods.
** Exercise3.
- what is lists?, list of sequense, list operations, list methods, list arguments and list with functions.
** Exercise4.
- what is tuples?, comparing tuples and sequenses of strings,lists and tuples.
* 2016-Apr-07-Thursday:
- I resumed my work on Python Programming Language.
** Exersice5.
- I have implemented source code for Looping concepts, string, lists and tuples.
