* 2016-Apr-25-Monday:
** From 10:00 AM TO 06:00 PM:
- Today *Madhavi* has assigned to me a task, the task is about *Restructuring of Vlabs landing page* Project. Here I have given task to convert all the required documents to org-mode format as per Madhavi's requirement.
- I have helped *Aswin* in installing =virtual box= and =KVM virtualization= on his desktop machine. And also I helped him in how to install windows xp on virtualbox.

* 2016-Apr-26-Tuesday:
** From 10:00 AM TO 06:00 PM:
- Today *Lalit* has assigned to me a task, the task is to convert all =docx= files to =org-mode= using emacs.
- I converted all suggested files to =org-mode=  And then I pushed to my forked repository on github. Then I made a pull request to actual =outreach-portal= repository unders =vlead= organization (This is because I don't have access to =vlead= organization).

* 2016-Apr-27-Wednesday:
** From 10:00 AM TO 01:00 PM:
- Today *Ashay* has assigned to me a task, the task is to install Ubuntu 12.04 on local machine for setting up edX in standalone machine.
- I have installed Ubuntu 12.04 64bit OS through bootable pendrive.

** From 02:00 PM TO 05:30 PM:
- I have installed ubuntu 14.04 64 bit OS on *RAVI's* machine as previously installed OS is crashed I tried to install two more times but after I had discussion with system team I came to that there is an issues the system =hardware= itself.

* 2016-Apr-28-Thursday:
** From 10:00 AM TO 05:00 PM:
- Today I discussed with team for getting a task, then they are assigned me a task, which is to install ubuntu 14.04 64bit OS on Prof. Choppella's new Dell machine.
- I have installed Ubuntu 14.04 64bit LTS OS through bootable pendrive.
- After successfull installation of ubuntu OS. I restarted machine and it worked well.
- After reboot machine, I have installed all the necessary packages. Below I have listed all the installed packages.
1. Ubuntu 14.04 64 bit (Beside Windows OS)
2. Emacs24.5 with org mode 8 version.
3. Setting up proxy in =.bashrc= file
4. Setting up proxy in =/etc/apt/apt.conf= file for apt to work via proxy
5. Google chrome
6. Skype 4.3
7. Git 1.7.2
8. Hex Chat

*Note:-*
- But some times machine is not booting properly , due to hardware inconsistancey.

* 2016-Apr-29-Friday:
** From 09:00 AM TO 05:30 PM:
 - I have gone through Literate Programming and installed latest
   version of emacs24.5 with org-mode8.3.4 on my machine. And also I followed below procedure for literate programming.
* Literate porgramming:
A Literate program generally consists of explanation of the code in a
natural language such as English, interspersed with snippets of code
to be executed. This means that Literate programs are very easy to
understand and share, as all the code is well explained.
* Procedure:
*Step 1:* Open emacs through terminal using command
 #+begin_src shell
 emacs <filename>
 #+end_src
*step 2:* make sure that file is in  =org-mode= if not change using
 #+begin_src shell
 M-x org-mode
 #+end_src 
*step 3:* Include profile using
#+begin_src shell
M-x org-insert-export-options-template
#+end_src
*step 4:* Include following properties and edit property of tangle =<filename>= w.r.t language (e.g hello.py, hello.java and hello.c)
#+begin_src shell 
#+PROPERTY: session *scratch*
#+PROPERTY: results output
#+PROPERTY: tangle <filename>
#+PROPERTY: exports code
#+end_src 
*step 5:* Start writing documentation followed by code make sure that code embeded in =#+begin_src python= and =#+end_src=
*step 6:* Now extract the source code from documentation using following cammand, It will prompt for file name give =<filename>.org= file as input
#+begin_src shell
M-x org-babel-tangle-file
#+end_src 
*step 7:* Now check tangle file in current directory if not exported kill the =<filename>.org= using =C-x k= and reload it.
