* (2016-07-18 Monday)
  - Checking alerts for VLEAD
  - Checking disk space of Outreach portal VM everyday as well as all the lab VMs.

  - I have removed all the 2016-interns related data from the attendance portal at (http://attendance.vlabs.ac.in). And before doing this I have taken database backup and tested back with restoring the same on base4 container (16298).
* (2016-07-19 Tuesday)
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - I and ashay created vlabs email-id for PVS Maruthi Rao and we shared credentials with him.
* (2016-07-20 Wednesday)
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - I and ashay created LDAP account  for PVS Maruthi Rao and we shared credentials with him.
  - Removed LDAP accounts for all  2016-summer interns. 
  - Exported couple of labs from [[http://edx-courses.vlabs.ac.in:18010][edx-cources]] into [[http://lms.vlabs.ac.in:18010][lms.vlabs.ac.in]].
  - Wrote a schell script for generating employee attendance daily wise, monthly wise reports with in-time and out-time for each employee.
* (2016-07-21 Thursday)
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - I have hosted couple of labs on base1 machine.
* (2016-07-22 Friday)
  - Checking alerts for VLEAD as well as  monitoring the services using  nagios webpage.
  - Generating the monthly wise employee attendance reports with in/out time details of each employee.
  - I have hosted couple of labs on base1 machine.
  - Exported couple of labs from [[http://edx-courses.vlabs.ac.in:18010][edx-cources]] into [[http://platform.vlabs.ac.in:18010][platform.vlabs.ac.in]].
  
